version: '3'
services:
    main-app:
        build:
            context: ../social-app/docker/8.2
            dockerfile: Dockerfile
        image: social-app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        volumes:
            - '../social-app:/var/www/html'
        networks:
            - social-app
        depends_on:
            - main-app-mysql
            - redis
    notification-service:
        build:
            context: ../social-app-notification-service/docker/8.2
            dockerfile: Dockerfile
        image: social-app-notification-service
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${NOTIFICATION_APP_PORT:-81}:80'
        volumes:
            - '../social-app-notification-service:/var/www/html'
        networks:
            - social-app
        depends_on:
            - notification-mysql
            - redis
    elastic-service:
        build:
            context: ../social-app-elasticsearch-service/docker/8.2
            dockerfile: Dockerfile
        image: social-app-elastic-service
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${ELASTIC_APP_PORT:-82}:80'
        volumes:
            - '../social-app-elasticsearch-service:/var/www/html'
        networks:
            - social-app
        depends_on:
            - elastic-mysql
            - elasticsearch
            - redis
    main-app-mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${MAIN_FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${MAIN_DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${MAIN_DB_DATABASE}'
            MYSQL_USER: '${MAIN_DB_USERNAME}'
            MYSQL_PASSWORD: '${MAIN_DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'social-app-mysql:/var/lib/mysql'
            - '../social-app/vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - social-app
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${MAIN_DB_PASSWORD}"]
            retries: 3
            timeout: 5s
    notification-mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${NOTIFICATION_FORWARD_DB_PORT:-3307}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${NOTIFICATION_DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${NOTIFICATION_DB_DATABASE}'
            MYSQL_USER: '${NOTIFICATION_DB_USERNAME}'
            MYSQL_PASSWORD: '${NOTIFICATION_DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'notification-app-mysql:/var/lib/mysql'
            - '../social-app-notification-service/vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - social-app
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${NOTIFICATION_DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
    elastic-mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${ELASTIC_FORWARD_DB_PORT:-3308}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${ELASTIC_DB_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${ELASTIC_DB_DATABASE}'
            MYSQL_USER: '${ELASTIC_DB_USERNAME}'
            MYSQL_PASSWORD: '${ELASTIC_DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'elastic-app-mysql:/var/lib/mysql'
            - '../social-app-elasticsearch-service/vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - social-app
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-p${ELASTIC_DB_PASSWORD}" ]
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'social-app-redis:/data'
        networks:
            - social-app
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        ports:
            - '2181:2181'
        environment:
            ALLOW_ANONYMOUS_LOGIN: 'yes'
        networks:
            - social-app
    kafka:
        image: 'bitnami/kafka:latest'
        ports:
            - '9092:9092'
        environment:
            KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            ALLOW_PLAINTEXT_LISTENER: 'yes'
        networks:
            - social-app
        depends_on:
            - zookeeper
    kafka-setup:
        image: 'bitnami/kafka:latest'
        depends_on:
            - kafka
        command: >
            bash -c "
              until echo > /dev/tcp/kafka/9092; do sleep 1; done
              /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic users &&
              /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic posts &&
              /opt/bitnami/kafka/bin/kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic comments
            "
        networks:
            - social-app
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
        environment:
            - discovery.type=single-node
            - ES_JAVA_OPTS=-Xms1g -Xmx1g
        ports:
            - '9200:9200'
        networks:
            - social-app
networks:
    social-app:
        driver: bridge
volumes:
    social-app-mysql:
        driver: local
    notification-app-mysql:
        driver: local
    elastic-app-mysql:
        driver: local
    social-app-redis:
        driver: local
